/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XnemAmbulanceWlList {
    }
}
declare global {
    interface HTMLXnemAmbulanceWlListElement extends Components.XnemAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXnemAmbulanceWlListElement: {
        prototype: HTMLXnemAmbulanceWlListElement;
        new (): HTMLXnemAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xnem-ambulance-wl-list": HTMLXnemAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XnemAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xnem-ambulance-wl-list": XnemAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xnem-ambulance-wl-list": LocalJSX.XnemAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXnemAmbulanceWlListElement>;
        }
    }
}
